name: Enceladus
description: Dynamic Conformance Engine

collections:
  docs:
    title: Documentation
    description: A collection of documentation pages for each version
    output: true
    permalink: :collection/:categories/:name

plugins:
  # https://help.github.com/en/articles/mentions-on-github-pages
  - jekyll-mentions

theme: jekyll-theme-midnight