---
  - name: conformance.allowOriginalColumnsMutability
    options:
    - name: boolean
      description: "Allows to modify/drop columns from the original input (default is <i>false</i>)"
  - name: conformance.autoclean.standardized.hdfs.folder
    options:
      - name: boolean
        description: 'Automatically delete standardized data folder after successful run of a Conformance job <sup><a href="#note1">*</a></sup>'
  - name: control.info.validation
    options:
    - name: <i>strict</i>
      description: Job will fail on failed _INFO file validation.
    - name: <i>warning</i>
      description: "(default) A warning message will be displayed on failed validation,
        but the job will go on."
    - name: <i>none</i>
      description: No validation is done.
  - name: enceladus.recordId.generation.strategy
    options:
    - name: <i>uuid</i>
      description: "(default) <code>enceladus_record_id</code> column will be added and will contain
        a UUID <code>String</code> for each row."
    - name: <i>stableHashId</i>
      description: "<code>enceladus_record_id</code> column will be added and populated with an
        always-the-same <code>Int</code> hash (Murmur3-based, for testing)."
    - name: <i>none</i>
      description: no column will be added to the output.
  - name: max.processing.partition.size
    options:
      - name: non-negative long integer
        description: 'Maximal size (in bytes) for the processing partition, which would influence the written parquet file size 
        <b>NB! Experimental - sizes might still not fulfill the requested limits</b>'
  - name: menas.rest.uri
    options:
    - name: string with URLs
      description: 'Comma-separated list of URLs where Menas will be looked for. E.g.:
        <code>http://example.com/menas1,http://domain.com:8080/menas2</code>'
  - name: menas.rest.retryCount
    options:
      - name: non-negative integer
        description: Each of the <code>menas.rest.uri</code> URLs can be tried multiple times for fault-tolerance
  - name: menas.rest.availability.setup
    options:
      - name: <i>roundrobin</i>
        description: "(default) Starts from a random URL from the <code>menas.rest.uri</code> list, if it fails the next
         one is tried, if last is reached start from 0 until all are tried"
      - name: <i>fallback</i>
        description: "Always starts from the first URL, and only if it fails the second follows etc."
  - name: min.processing.partition.size
    options:
      - name: non-negative long integer
        description: 'Minimal size (in bytes) for the processing partition, which would influence the written parquet file size 
        <b>NB! Experimental - sizes might still not fulfill the requested limits</b>'
  - name: standardization.defaultTimestampTimeZone.default
    options:
    - name: string with any valid time zone name
      description: The time zone for normalization of timestamps that don't have their own time zone either in data
        itself or in metadata. If left empty the system time zone will be used.
  - name: standardization.defaultTimestampTimeZone.[rawFormat]
    options:
      - name: string with any valid time zone name
        description: Same as above <code>standardization.defaultTimestampTimeZone.default</code>, but applies only for
          the specific input raw format - then it takes precedence over
          <code>standardization.defaultTimestampTimeZone.default</code>.
  - name: standardization.defaultDateTimeZone.default
    options:
    - name: string with any valid time zone name
      description: The time zone for normalization of dates that don't have their own time zone either in data itself
        or in metadata in case they need it. Most probably this should be left undefined.
  - name: standardization.defaultDateTimeZone.[rawFormat]
    options:
      - name: string with any valid time zone name
        description: Same as above <code>standardization.defaultDateTimeZone.default</code>, but applies only for
          the specific input raw format - then it takes precedence over
          <code>standardization.defaultDateTimeZone.default</code>.
  - name: timezone
    options:
    - name: string with any valid time zone name
      description: The time zone the Spark application will operate in. Strongly recommended
        to keep it to default <i>UTC</i>
